### ISSUE TITLE
Use Existing not working

### ISSUE THREAD

**Issue by aabaricalla** [Gaius-Augustus/GALBA#22]
Hi @KatharinaHoff, 
I'm testing GALBA.
Today I launch the pipeline and, after a few internal problems, I have to relaunch it using the "--useexisting" option (derived from Braker) but GALBA doesn't recognize it even when the log file suggest it.

 I do not have the results yet, but I'm anxious to have it.

Cheers!

**Comment by KatharinaHoff** [comment]
Thanks!

I will go through the code to remove all traces of that option. Please use
skipAllTraining.

Agustin Baricalla ***@***.***> schrieb am Di. 14. März 2023
um 20:37:

**Comment by KatharinaHoff** [comment]
Addressed in https://github.com/Gaius-Augustus/GALBA/commit/82a827686076bb28d40354fcc73a5614a0ba0f60

Thank you!
