### ISSUE TITLE
Protein.fa files

### ISSUE THREAD

**Issue by zhoudreames** [Gaius-Augustus/GALBA#28]
I have no-human genome（pig）, and I want to do gene annotation for it. but I don't know how to choose the protein files, Should I only choose a pig protein file or can I combine multiple species. Thanks~

**Comment by KatharinaHoff** [comment]
I recommend to choose 4 or more protein sets (e.g. pig, human, mouse, … and
maybe goat or cow or even both). Concatenate the files, simplify headers.

We have previously looked into pig. Sus scrofa has a decent annotation.

It is important to repeat mask the genome, first.

zhoudreames ***@***.***> schrieb am Di. 11. Apr. 2023 um
02:57:

**Comment by zhoudreames** [comment]
> We have previously looked into pig. Sus scrofa has a decent annotation

Thank you for your detail response， I try it.
