### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aabaricalla** [Gaius-Augustus/GALBA#30]
Hi @KatharinaHoff ! 
I was wondering if there is any date for the release of the GALBA docker image with [Miniprot-0.10 (r225)](https://github.com/lh3/miniprot/releases/tag/v0.10)?

I have a "segmentation fault" error that Miniprot could be responsible for... And @lh3 reported this issue was solved in the 0.10 release version. 

Thanks!

**Comment by KatharinaHoff** [comment]
I will compile a new container this weekend. Sorry! I

Agustin Baricalla ***@***.***> schrieb am Fr. 14. Apr. 2023
um 19:52:

**Comment by KatharinaHoff** [comment]
I have just pushed an update to dockerhub. Please pull the latest image once more, and try again.

I apologize for not having done this, sooner. I was traveling.

**Comment by aabaricalla** [comment]
Thanks a lot @KatharinaHoff !
I will be testing it in a while.
Your work in GALBA is wonderful.
Saludos desde Argetina.-

**Comment by KatharinaHoff** [comment]
Is this issue solved?

**Comment by KatharinaHoff** [comment]
I strongly assume this issue was solved.

**Comment by aabaricalla** [comment]
Thanks for the improvements. This issue was solved with the update in docker!
