### ISSUE TITLE
failed to execute miniprothint.py

### ISSUE THREAD

**Issue by COMInterop** [Gaius-Augustus/GALBA#31]
Hello,

This may be a continuation of https://github.com/Gaius-Augustus/GALBA/issues/20.

I am running the Docker container on a Mac. The program terminates with the following error:

[Sat Apr 22 04:41:12 2023] error: exited due to an error in command: grep stop_codon /Volumes/data/annotate/galba/miniprot.gff | grep proteinEnd=1 > /Volumes/data/annotate/galba/tmp/stopsAllEndcbot99o4.gff
ERROR in file /opt/GALBA/scripts/galba.pl at line 3345
failed to execute: /opt/miniprothint/miniprothint.py /Volumes/data/annotate/galba/miniprot.gff --workdir /Volumes/data/annotate/galba --ignoreCoverage!

I see you asked the previous poster to 'share a couple of proteins that produce this error'. How can I know which ones are problematic? 

Thank you!

**Comment by tomasbruna** [comment]
Hi @paracontias,

if you can upload your whole input somewhere, I'd take a look. No need to hunt for individual sequences.

Tomas

**Comment by COMInterop** [comment]
I just emailed it to you

**Comment by KatharinaHoff** [comment]
I assume that this issue was resolved a while ago.

**Comment by tomasbruna** [comment]
Yes resolved. I think this was caused by using input proteins with stops in them (a '*' in the line ends). This was fixed in https://github.com/tomasbruna/miniprot-boundary-scorer/commit/a4c3ab1222e8351f1c39c5776e576d45e2ca2529
