### ISSUE TITLE
pygustus_hints.err

### ISSUE THREAD

**Issue by linshengnan09** [Gaius-Augustus/GALBA#41]
hi, I encountered an error when using GALBA for homology prediction. the err.log as follows:
####
ERROR in file $home/02biosoft/GALBA-1.0.8/scripts/galba.pl at line 5200
Failed to execute: $home/miniconda3/envs/GALBA/bin/python3 $home/03work/04hZ/05revio/08anno/02As/05homology_GALBA/GALBA/pygustus_hints.py 1> $home/03work/04hZ/05revio/08anno/02As/05homology_GALBA/GALBA/pygustus_hints.out 2>$home/03work/04hZ/05revio/08anno/02As/05homology_GALBA/GALBA/errors/pygustus_hints.err
####
pygustus_hints.err:
Traceback (most recent call last):
  File "$home/03work/04hZ/05revio/08anno/02As/05homology_GALBA/GALBA/pygustus_hints.py", line 9, in <module>
    augustus.predict('$home/03work/04hZ/05revio/08anno/02As/05homology_GALBA/GALBA/genome.fa', species='As_galba', partitionLargeSequences=True, partitionHints=True, minSplitSize=1000000, chunksize=2500000, jobs=10, **augargs)
  File "$home/miniconda3/envs/GALBA/lib/python3.12/site-packages/pygustus/augustus.py", line 51, in predict
    util.check_aug_version(augustus_command, MIN_AUG_VERSION)
  File "$home/miniconda3/envs/GALBA/lib/python3.12/site-packages/pygustus/util.py", line 168, in check_aug_version
    raise RuntimeError(
RuntimeError: AUGUSTUS version 3.3.2 or higher is required!
####
The AUGUSTUS version I installed was 3.5.0

![微信图片_20231108161207](https://github.com/Gaius-Augustus/GALBA/assets/45194038/18d5309a-24f7-4c82-b74e-65798efecd99)

I don't know how to solve this error. Do you have any suggestions?
Thank you!

**Comment by KatharinaHoff** [comment]
Pygustus and Augustus are sadly a bit out of sync. We are somehow not smart enough to make sure that a parameters file ends up in the debian package of Augustus - so sorry for that. The GitHub Augustus has that file.

In the container, I patch Augustus as follows:

```
RUN cd /usr/share/augustus/config && \
    mkdir parameters && \
    cd parameters && \
    wget https://raw.githubusercontent.com/Gaius-Augustus/Augustus/master/config/parameters/AUG_CMDLN_PARAMETERS.md && \
    wget https://raw.githubusercontent.com/Gaius-Augustus/Augustus/master/config/parameters/aug_cmdln_parameters.json && \
    chmod a+r AUG_CMDLN_PARAMETERS.md aug_cmdln_parameters.json && \
    cd .. && \
    chmod a+r parameters && \
    chmod a+x parameters
```
Please check whether your Augustus has the parameters folder with these two files. If now, just add them as I do in the container.

If you obtained your Augustus from GitHub, then this will not be the cause of the problem and we need to look further.

**Comment by linshengnan09** [comment]
I installed Augustus from micromamba. And I have checked the Augustus and there has the parameters folder with these two files.

 
![image](https://github.com/Gaius-Augustus/GALBA/assets/45194038/9e24aed6-4370-4259-8b43-a8f1ced38692)

**Comment by KatharinaHoff** [comment]
As I said, pygustus and augustus were at some point in time out of sync. I recommend that you use your singularity container because there I make sure compatible versions are indeed used. I tested the novel container, today, and it works.

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！
