### ISSUE TITLE
gbFilterEtraining.stderr error

### ISSUE THREAD

**Issue by gushiro** [Gaius-Augustus/GALBA#42]
Hi,

I run before GALBA with no problems. But now I include more proteins and I am having an error. This is the end go the error file:

```
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 94172 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 94375 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 95155 annotations.
GBProcessor::getGeneList(): Could not read the following line in Genbank file.
tgaaagtcaa agtgtgagtg tatgtgaaac aaaagaagtc atttgtccgt
Maximum line length is 
39998.

Encountered error after reading 96404 annotations.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

PD: I am using GALBA from Singularity.

Thank you for your help!

**Comment by gushiro** [comment]
To follow this up, the problem does not seem to appear when I run a set of proteins from a single species reference

**Comment by KatharinaHoff** [comment]
@MarioStanke is the Maximum line length something that play a role, here? Can I prevent this in GALBA somehow, or better: should I? Or should it be fixed in etraining?

**Comment by MarioStanke** [comment]
No, the line is short. But maybe it is wrong in its context. I would check the neighboring lines for oddities.

**Comment by KatharinaHoff** [comment]
I pushed a new docker container, today. The new container builds etraining from github (previously we used the Debian package version). Maybe this solves your problem. If it does not solve your problem, feel free to open a well-documented augustus issue int he Augustus repository. Ideally, provide a small train.gb file that leads to the segmentation fault.
