### ISSUE TITLE
error: exited due to an error in command: grep intron 

### ISSUE THREAD

**Issue by qussai96** [Gaius-Augustus/GALBA#44]
Dear Katharina,

Thank you for your work on BRAKER and GALBA - great tools!

I've been trying to run GALBA, but encountered an error:
```
error: exited due to an error in command: grep intron /proj/q.abbas/MT/3-Galba/MT/miniprot_representatives.gff > /proj/q.abbas/MT/3-Galba/MT/tmp/intronsAlldk1ut2i9.gff
ERROR in file /home/Tools/GALBA-main/scripts/galba.pl at line 3546
failed to execute: /home/Tools/miniprot/miniprothint/miniprothint.py /proj/q.abbas/MT/3-Galba/MT/miniprot.gff --workdir /proj/q.abbas/MT/3-Galba/MT --ignoreCoverage --topNperSeed 10 --minScoreFraction 0.5!
```
The miniprot_representatives.gff file is empty. Even after increasing the protein database size to around 100,000 proteins, the issue persists. I've attached the GALBA.log file for your reference.

Appreciate your help!

Cheers,
Qussai
[GALBA.log](https://github.com/Gaius-Augustus/GALBA/files/13974485/GALBA.log)

**Comment by tomasbruna** [comment]
Hi @qussai96,

it looks like something went wrong during the protein alignment. Would you mind sharing your input files (send by e-mail if you don't want to share them here)? I'll try to reproduce the issue on my end. Please share only the small protein database input, that should be enough to reproduce the problem.

Tomas

**Comment by qussai96** [comment]
Thank you @tomasbruna for the response.
I have sent the input files by email.

best,
Qussai

**Comment by qussai96** [comment]
Thanks to Tomas, I resolved the issue by pulling the latest version of miniprot-boundary-scorer "https://github.com/tomasbruna/miniprot-boundary-scorer".
