### ISSUE TITLE
Error regarding pygustus in singularity run

### ISSUE THREAD

**Issue by stat-lab** [Gaius-Augustus/GALBA#46]
Thank you for providing the fantastic annotation pipeline.
I built the latest singularity sif container according to README, and executed the following command.
singularity exec --bind $HOME,${input_file_dir} galba.sif galba.pl --genome=genome.fa --prot_seq=protein.fa --species=species3 --threads 8

Failed to execute: /opt/conda/bin/python3 ${work_dir}/GALBA/pygustus_hints.py 1> ${work_dir}/GALBA/pygustus_hints.out 2>${work_dir}/GALBA/errors/pygustus_hints.err

The content of pygustus_hints.err:

Traceback (most recent call last):
  File "${work_dir}/GALBA/pygustus_hints.py", line 9, in <module>
    augustus.predict('/sdisk02/kosugi/C.elegans/GALBA/Cremanei_Cbriggsae/GALBA/genome.fa', species='galba_elegans4', partitionLargeSequences=True, partitionHints=True, minSplitSize=1000000, chunksize=2500000, jobs=8, **augargs)
  File "/opt/conda/lib/python3.10/site-packages/pygustus/augustus.py", line 42, in predict
    pygustus_options = util.get_options(
  File "/opt/conda/lib/python3.10/site-packages/pygustus/util.py", line 115, in get_options
    options = AugustusOptions(
  File "/opt/conda/lib/python3.10/site-packages/pygustus/options/aug_options.py", line 87, in __init__
    self.set_value(option, value)
  File "/opt/conda/lib/python3.10/site-packages/pygustus/options/aug_options.py", line 101, in set_value
    raise ValueError(
ValueError: Invalid Parameter for Augustus: partitionLargeSequences

The permission of /opt/conda/lib/python3.10/site-packages/pygustus/options/aug_options.py seems to be unexecutable.
-rw-rw-r-- 1 root root 6591 Feb 13 22:03 /opt/conda/lib/python3.10/site-packages/pygustus/options/aug_options.py

Previous issues related to this problem seems to be solved by using the latest singulrity image, but I used the latest one, and no AUGUSTUS_CONFIG_PATH is set.

It would be helpful to let me know how to solve the problem.

**Comment by KatharinaHoff** [comment]
Have you removed a previously existing directory ~/.augustus or
$PWD/.augustus ?

**Comment by stat-lab** [comment]
Thank you very much for your prompt response. I successfully completed my runs after removing ~/.augustus directory that had been created for another tool, BRAKER3.

I often execute GRAKER3 with the singularity container, which also creates .augustus directory in $HOME directory.
Is the ~/.augustus directory used by GALBA and BRAKER3 compatible? After running BRAKER3, can GALBA use the same ~/.augustus directory?

**Comment by KatharinaHoff** [comment]
The same directory can be used. Problems arise with older AUGUSTUS config
files in that directory.

stat-lab ***@***.***> schrieb am Sa. 2. März 2024 um 10:53:

**Comment by stat-lab** [comment]
I understand. Thank you.
