### ISSUE TITLE
Intall

### ISSUE THREAD

**Issue by zhangyixing3** [Gaius-Augustus/GALBA#47]
Our linux do not have singularity, Can We install  GALBA by conda ?

**Comment by KatharinaHoff** [comment]
You need the latest Augustus because of a change in the config folder and
also several bugfixes. If you can compile that on your system, you can
install the other dependencies via conda rather easily.

Zhang Yixing ***@***.***> schrieb am Mi. 6. März 2024 um
07:52:

**Comment by zhangyixing3** [comment]
Thank you for your advice. I'll try.
