### ISSUE TITLE
Error regarding pygustus in singularity run: "No space left on device" 

### ISSUE THREAD

**Issue by maxnest** [Gaius-Augustus/GALBA#50]
Dear colleagues,
Thank you for developing an extremely useful pipeline!
Unfortunately, I encountered some difficulties. On a local computer, the pipeline performed well when working with one of the genomes. However, when running the pipeline on a remote server, after 3 hours of analysis, the pipeline send the following error (GALBA.log):

"...
Thu Apr 11 16:14:34 2024: RUNNING AUGUSTUS
Thu Apr 11 16:14:34 2024: AUGUSTUS with hints
Thu Apr 11 16:14:34 2024: copy extrinsic file /opt/GALBA/scripts/cfg/galba.cfg to working directory
cp /opt/GALBA/scripts/cfg/galba.cfg /scratch/project_2000784/GALBA_test/New_test/species/Lolivaceus_container_2/ex1.cfg
/opt/conda/bin/python3 /scratch/project_2000784/GALBA_test/New _test/pygustus_hints.py 1> /scratch/project_2000784/GALBA_test/New_test/pygustus_hints.out 2>/scratch/project_2000784/GALBA_test/New_test/errors/pygustus_hints.err"

The last ten lines of the pygustus_hints.err: 
"...
    util.execute_bin_parallel(
  File "/opt/conda/lib/python3.10/site-packages/pygustus/util.py", line 32, in execute_bin_parallel
    run_information = fm.split(
  File "/opt/conda/lib/python3.10/site-packages/pygustus/fasta_methods.py", line 97, in split
    write_file([seq_record], inputfile, outputdir, fileidx)
  File "/opt/conda/lib/python3.10/site-packages/pygustus/fasta_methods.py", line 156, in write_file
    SeqIO.write(records_to_write, splitpath, 'fasta')
  File "/opt/conda/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 524, in write
    fp.write(format_function(record))
OSError: [Errno 28] No space left on device"

At the same time, the server has slightly less than 1 TB of free space available for storing files.
I run GALBA through a container and tried to specify different directories for writing files:

_nohup apptainer exec -H $WORKDIR:/home/mnestere -B $WORKDIR:$WORKDIR $GALBA galba.pl --species=${SPECIES} --gff3 --threads $THREADS --workingdir=${WORKDIR} --genome=${FASTA} --prot_seq=${REFPROTEINS}_

I would be grateful for any help!
Maksim

**Comment by KatharinaHoff** [comment]
Pygustus tries to write in /tmp on the machine.

**Comment by KatharinaHoff** [comment]
I will close this issue because it's not really a software issue.
